### ISSUE TITLE
Figure out how to turn off autocorrect and do so where applicable (username, email, insurance provider, etc).

### ISSUE THREAD

**Issue by DevenHurt** [Utagai/MedKit#15]

**Comment by Utagai** [comment]
See this SO thread. A simple solution, since the TextField objects have functionality for handling user inputs that correspond to things like email, username, password and so on:
http://stackoverflow.com/questions/2474824/iphone-issue-disabling-auto-cap-autocorrect-on-a-uitextfield

**Comment by DevenHurt** [comment]
It looks good! Thanks!
