### ISSUE TITLE
Come up with a check to see if a string is numeric

### ISSUE THREAD

**Issue by DevenHurt** [Utagai/MedKit#19]

**Comment by Utagai** [comment]
Try Swift's String method toInt(). If you read up on it, non-numeric strings return nil. The resulting algorithm is trivial:

var myNumStr: String = "85829532"
var myNonNumStr: String = "hello4!"

var myNumInt: Int = myNumStr.toInt()
var myNonNumInt: Int = myNonNumStr.toInt()

myNumInt has the value 85829532. myNonNumInt is nil.

**Comment by Utagai** [comment]
Doing some actual testing, it seems like toInt() has been deprecated as of Swift 2. Doing some more looking, using Int(myStr) would be the way to go now, which works like this:

if let myNum = Int(myStr){
//its a num!
} else {
//its not a num!
}

**Comment by DevenHurt** [comment]
Swag!
